name: SMPTools
version: '${project.version}'
main: org.phlyer.smptools.SMPTools
api-version: '1.20'
commands:
  waypoint:
    aliases: wp
    description: Opens the Waypoint GUI.
    usage: /waypoint
  pdc:
    permissions: op