name: SMPTools
version: '${project.version}'
main: org.phlyer.smptools.SMPTools
api-version: '1.20'
commands:
  waypoint:
    aliases: wp
    description: Opens the Waypoint GUI.
    usage: "/command"
  pdc:
    permissions: op
  coords:
    description: Broadcasts your coordinates.
    usage: "/command <arg>"